#!/usr/bin/env python3
"""
Repair / refresh the AI-BEAST folder layout.

Run this inside the folder that contains app.py:

    python setup_files.py

Rewrites templates/ with the current six HTML files, creates static/, moves
style.css and task.js into static/ if they are loose, then version-checks the
files it does not own. Safe to re-run.
"""
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent

TEMPLATES = {}
TEMPLATES['base.html'] = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{% block title %}Dot estimation study{% endblock %}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>
"""
TEMPLATES['consent.html'] = r"""{% extends "base.html" %}
{% block body %}
<div class="wrap">
  <h1>Dot estimation with an AI assistant</h1>

  <p>This study looks at how people estimate quantities and how they use written advice from an
  AI assistant. It takes about 40–45 minutes.</p>

  <h2>What you'll do</h2>
  <ul>
    <li>You'll see images containing many dots, one at a time.</li>
    <li>For each image you give a first estimate of how many dots there are.</li>
    <li>An AI assistant then gives you a written estimate.</li>
    <li>You give a final estimate. After every two trials, you answer two short questions about trust and how the advice made you feel.</li>
    <li>There are 104 images in total, split into 8 rounds, with a checkpoint and optional break between rounds.</li>
    <li><strong>You will never be told the correct number of dots.</strong> There is no score and no feedback on accuracy.</li>
  </ul>

  <h2>Things to know before you agree</h2>
  <ul>
    <li>The AI assistant's estimates are generated for the purposes of this study and are
    <strong>not</strong> guaranteed to be accurate. Please treat them as one input, not as a correct answer.</li>
    <li>Some details of the study design are withheld until the end so they don't influence your
    responses. You'll get a full explanation on the final page, and you can withdraw your data then.</li>
    <li>Your responses are stored under a random code, not your name.</li>
    <li>You can stop at any point by closing the tab, without giving a reason.</li>
  </ul>

  <!-- REPLACE the block below with the wording approved by your HREC. -->
  <p class="small muted">Contact and ethics approval details go here (researcher name, institution,
  HREC reference, data-protection contact, data retention period).</p>

  <hr>

  <form method="post" action="{{ url_for('start') }}">
    <input type="hidden" name="external_id" value="{{ external_id }}">
    {% if researcher_mode %}
    <div class="researcher-test-panel">
      <h2>Researcher test controls</h2>
      <input type="hidden" name="researcher_test" value="1">
      <label>Condition to test
        <select name="conditions">
          <option value="">All 8 conditions</option>
          {% for cid, info in condition_defs.items() %}
          <option value="{{ cid }}" {% if conditions == cid %}selected{% endif %}>{{ cid }} — {{ info.label }}</option>
          {% endfor %}
        </select>
      </label>
      <label>Trials in the selected condition
        <input type="number" name="trials" min="1" max="13" value="{{ trials or 13 }}">
      </label>
      <label>Counterbalancing row for this TEST session
        <select name="test_index">
          {% for i in range(8) %}<option value="{{ i }}" {% if test_index|int == i %}selected{% endif %}>Row {{ i + 1 }} (participant index {{ i }})</option>{% endfor %}
        </select>
      </label>
      <label class="checkline"><input type="checkbox" name="skip_practice" value="1" {% if skip_practice %}checked{% endif %}> Skip practice</label>
      <p class="small muted">Researcher sessions are marked TEST and do not consume the production counterbalancing sequence.</p>
    </div>
    {% endif %}
    <p><label><input type="checkbox" required> I have read the above, I am 18 or older, and I agree to take part.</label></p>
    <button type="submit">Start</button>
  </form>
</div>
{% endblock %}
"""
TEMPLATES['debrief.html'] = r"""{% extends "base.html" %}
{% block body %}
<div class="wrap">
  <h1>You're finished — thank you</h1>

  <h2>What the study was really testing</h2>
  <p>You were told the AI assistant's estimates might not be accurate. In fact the numerical
  recommendations were set by the experiment rather than generated by an AI trying to be correct.</p>
  <ul>
    <li>In two rounds the recommendations were close to the true count, or close to your own first estimate.</li>
    <li>In three rounds the fixed recommendation schedule averaged 25% above the correct count.</li>
    <li>In three rounds the fixed recommendation schedule averaged 25% below the correct count.</li>
  </ul>

  <p>Within the three higher-advice rounds the numerical recommendations followed the same fixed
  schedule, and the same was true within the three lower-advice rounds. What changed was how the
  assistant worded the recommendation: neutrally in one round, persuasively in another, and in a
  third it could use everything that had happened earlier in that round to tailor its persuasion.</p>

  <p>The persuasive messages were generated to maximise the chance that you would move toward the
  fixed recommendation. In the adaptive rounds, the assistant could use your earlier estimates,
  final answers, ratings, and its own earlier messages from that round.</p>

  <p>We're testing whether an AI that adapts to a person's previous behaviour shifts judgement more
  than an AI that does not, while holding the numerical advice constant. We could not explain this
  manipulation beforehand because knowing the advice policy would change how people respond to it.</p>

  <p>The round checkpoints you saw were only progress markers. They did not reflect your accuracy,
  agreement with the AI, or performance.</p>

  <h2>Your data</h2>
  <p>Your responses are stored under a random code. If you'd rather we didn't use them,
  contact us with your code and we'll delete them, no questions asked.</p>

  <!-- REPLACE with your approved contact block and participant code display. -->
  <p class="small muted">Researcher contact, HREC reference, and withdrawal instructions go here.</p>

  <p>You can close this tab now.</p>
</div>
{% endblock %}
"""
TEMPLATES['instructions.html'] = r"""{% extends "base.html" %}
{% block body %}
<div class="wrap">
  <h1>How each trial works</h1>
  <ol>
    <li>A dot image appears. Look at it and make a first estimate.</li>
    <li>The image disappears and you type your first estimate.</li>
    <li>The AI assistant shows you a written estimate.</li>
    <li>You type your final estimate. It can be the same as your first, or different.</li>
    <li>After every two trials, you answer two short questions about trust and how the advice made you feel.</li>
  </ol>

  <p>Don't try to count the dots one by one; estimating is the point. You will not be told the
  correct number at any point.</p>

  <h2>Eight rounds</h2>
  <p>The 104 trials are split into 8 rounds of 13. A small progress track and checkpoint screen
  show how far through the study you are. They are <strong>not</strong> a score and do not tell you
  whether your answers are accurate.</p>
  <p>To keep the task moving, the two short rating questions appear only after every second trial.</p>

  <h2>One warm-up trial first</h2>
  <p>These use the same image → estimate → advice → final-answer sequence and aren't recorded.</p>

  <div class="center"><a href="{{ url_for('task') }}"><button>Begin practice</button></a></div>
</div>
{% endblock %}
"""
TEMPLATES['rate.html'] = r"""{% extends "base.html" %}
{% block body %}
<div class="wrap wide">
  <h1>Rate these messages</h1>
  <p>Each message below was shown to someone during a dot-estimation task. Rate each one on
  its own terms. You are not told who wrote it or what condition it came from.</p>
  <p class="small muted">Rater code: {{ rater }}</p>

  {% for it in items %}
  <div class="rate-item" data-trial="{{ it.id }}">
    <div class="msg">{{ it.advice_text }}</div>
    <div class="scales"></div>
    <button class="save" disabled>Save rating</button>
    <span class="small muted status"></span>
  </div>
  {% else %}
  <p>No messages left to rate.</p>
  {% endfor %}
</div>
<script>
const RATER = "{{ rater }}";
const DIMS = [
  ["personalization","How personalized to this individual does it feel?","Not at all","Highly"],
  ["warmth","How warm is it?","Cold","Warm"],
  ["valence","How positive is its tone?","Very negative","Very positive"],
  ["directiveness","How strongly does it tell the reader what to do?","Not at all","Very strongly"],
  ["convincingness","How convincing is it?","Not at all","Very"]
];
document.querySelectorAll('.rate-item').forEach(item => {
  const box = item.querySelector('.scales');
  box.innerHTML = DIMS.map(([k,q,lo,hi]) => {
    const id = k + '_' + item.dataset.trial;
    let o = ''; for (let i=1;i<=7;i++) o += `<label><input type="radio" name="${id}" value="${i}"><span>${i}</span></label>`;
    return `<div class="scale"><div class="q">${q}</div><div class="opts">${o}</div>
            <div class="anchors"><span>${lo}</span><span>${hi}</span></div></div>`;
  }).join('');
  const btn = item.querySelector('.save');
  box.querySelectorAll('input').forEach(i => i.onchange = () => {
    btn.disabled = DIMS.some(([k]) => !item.querySelector(`input[name=${k}_${item.dataset.trial}]:checked`));
  });
  btn.onclick = async () => {
    const body = {rater_id: RATER, trial_id: +item.dataset.trial};
    DIMS.forEach(([k]) => body[k] = +item.querySelector(`input[name=${k}_${item.dataset.trial}]:checked`).value);
    await fetch('/api/rate', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body)});
    btn.disabled = true; item.querySelector('.status').textContent = 'Saved';
  };
});
</script>
{% endblock %}
"""
TEMPLATES['task.html'] = r"""{% extends "base.html" %}
{% block body %}
<div class="progress"><i id="bar" style="width:0%"></i></div>
<div class="round-track" id="round-track"><span class="warmup-chip">Warm-up</span></div>
<div class="meta" id="meta"></div>
<div class="wrap"><div class="stage" id="stage"></div></div>
{% if researcher_mode %}<div id="rmode" class="rmode"></div>{% endif %}
<script>
window.BEAST_CFG = {
  min_delay_ms: {{ min_delay }},
  stimulus_ms: {{ stimulus_ms }},
  collect_ratings: {{ collect_ratings }},
  rating_every: {{ rating_every }},
  prefill_final: {{ prefill_final }},
  researcher_mode: {{ researcher_mode }}
};
</script>
<script src="{{ url_for('static', filename='task.js') }}"></script>
{% endblock %}
"""


def main():
    if not (HERE / "app.py").exists():
        raise SystemExit("Run this from the folder that contains app.py.")

    tdir = HERE / "templates"
    tdir.mkdir(exist_ok=True)
    for name, body in TEMPLATES.items():
        (tdir / name).write_text(body, encoding="utf-8")
        print(f"wrote templates/{name}")

    sdir = HERE / "static"
    sdir.mkdir(exist_ok=True)
    for asset in ("style.css", "task.js"):
        loose = HERE / asset
        if loose.exists():
            shutil.move(str(loose), str(sdir / asset))
            print(f"moved {asset} -> static/{asset}")
        elif (sdir / asset).exists():
            print(f"static/{asset} already in place")
        else:
            print(f"MISSING: {asset} — download it into static/")

    stim = sdir / "stimuli"
    n = len(list(stim.glob("*.png"))) if stim.exists() else 0
    print(f"\nstatic/stimuli: {n} images" + ("" if n >= 105 else "  -> run: python stimuli.py --size 512 --force"))

    ana = HERE / "analysis.R"
    if ana.exists():
        (HERE / "analysis").mkdir(exist_ok=True)
        shutil.move(str(ana), str(HERE / "analysis" / "analysis.R"))
        print("moved analysis.R -> analysis/analysis.R")

    print("\nversion check")
    checks = [
        ("app.py", "RESEARCHER_MODE", "researcher overlay (server)"),
        ("app.py", "only_conditions", "condition filter for test sessions"),
        ("app.py", 'STIMULUS_MS", "5000', "timed stimulus default"),
        ("app.py", "RATING_EVERY", "ratings every N trials"),
        ("app.py", "admin_downloads", "researcher download page"),
        ("adviser.py", 'ADVISER_MODEL = os.getenv("ADVISER_MODEL", "gpt-5")', "GPT-5 adviser default"),
        ("adviser.py", "REPETITION_SIMILARITY_LIMIT", "anti-repetition validation"),
        ("adviser.py", "everything that happened earlier in this block", "historical adaptive persuasion"),
        ("adviser.py", "message_is_valid", "mechanical message validation"),
        ("static/task.js", "renderResearcher", "researcher overlay (client)"),
        ("static/task.js", "checkpointMarkup", "progress-only gamification"),
        ("static/task.js", "askForAnswer", "two-phase timed presentation"),
        ("static/style.css", ".checkpoint-card", "checkpoint styles"),
    ]
    missing = False
    for rel, needle, what in checks:
        f = HERE / rel
        ok = f.exists() and needle in f.read_text(encoding="utf-8")
        print(f"  [{'ok' if ok else 'OLD'}] {what}")
        missing |= not ok
    if missing:
        print("\nRe-download the files marked OLD.")
    else:
        print("\nAll current. Run:")
        print("  RESEARCHER_MODE=1 PORT=5123 python app.py")


if __name__ == "__main__":
    main()
